/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import civitas.CasillaCalle;
import civitas.Jugador;
import java.util.ArrayList;

/**
 *
 * @author Blanca
 */
public class JugadorPanel extends javax.swing.JPanel {

    /**
     * Creates new form JugadorPanel
     */
    
    Jugador jugador;
    
    public JugadorPanel() {
        initComponents();
    }
    
    public void setJugador(Jugador j){
        jugador = j;
        campo_nombre.setText(j.getNombre());
        campo_saldo.setText(Float.toString(j.getSaldo()));
        campo_especulador.setText(Boolean.toString(j.soyEspeculador()));
        rellenaPropiedades(j.getPropiedades());
        this.repaint();
        this.revalidate();
    }
    
    public void rellenaPropiedades(ArrayList<CasillaCalle> lista){
        // se elimina la información antigua
        propiedadesPanel.removeAll();
        // Se recorre la lista de propiedades para ir creando sus vistas individuales y añadirlas al panel
        for(CasillaCalle t : lista){
            PropiedadPanel vistaPropiedad = new PropiedadPanel();
            vistaPropiedad.setPropiedad(t);
            propiedadesPanel.add(vistaPropiedad);
            vistaPropiedad.setVisible(true);
        }
        // Se fuerza la actualización visual del panel propiedades y del panel del jugador
        repaint();
        revalidate();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nombre = new javax.swing.JLabel();
        campo_nombre = new javax.swing.JTextField();
        saldo = new javax.swing.JLabel();
        campo_saldo = new javax.swing.JTextField();
        especulador = new javax.swing.JLabel();
        campo_especulador = new javax.swing.JTextField();
        propiedadesPanel = new javax.swing.JPanel();
        propiedadPanel1 = new GUI.PropiedadPanel();

        nombre.setText("Nombre:");
        add(nombre);

        campo_nombre.setEditable(false);
        campo_nombre.setColumns(5);
        campo_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_nombreActionPerformed(evt);
            }
        });
        add(campo_nombre);

        saldo.setText("Saldo:");
        add(saldo);

        campo_saldo.setEditable(false);
        campo_saldo.setColumns(5);
        campo_saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_saldoActionPerformed(evt);
            }
        });
        add(campo_saldo);

        especulador.setText("Especulador:");
        add(especulador);

        campo_especulador.setEditable(false);
        campo_especulador.setColumns(5);
        campo_especulador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campo_especuladorActionPerformed(evt);
            }
        });
        add(campo_especulador);

        propiedadesPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        propiedadesPanel.setMaximumSize(new java.awt.Dimension(120, 120));
        propiedadesPanel.setMinimumSize(new java.awt.Dimension(120, 120));

        propiedadPanel1.setAutoscrolls(true);
        propiedadesPanel.add(propiedadPanel1);

        add(propiedadesPanel);
    }// </editor-fold>//GEN-END:initComponents

    private void campo_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_nombreActionPerformed

    private void campo_saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_saldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_saldoActionPerformed

    private void campo_especuladorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campo_especuladorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campo_especuladorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campo_especulador;
    private javax.swing.JTextField campo_nombre;
    private javax.swing.JTextField campo_saldo;
    private javax.swing.JLabel especulador;
    private javax.swing.JLabel nombre;
    private GUI.PropiedadPanel propiedadPanel1;
    private javax.swing.JPanel propiedadesPanel;
    private javax.swing.JLabel saldo;
    // End of variables declaration//GEN-END:variables
}
