/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import civitas.CasillaCalle;
/**
 *
 * @author Blanca
 */
public class PropiedadPanel extends javax.swing.JPanel {

    CasillaCalle tituloPropiedad;
    
    /**
     * Creates new form PropiedadPanel
     */
    public PropiedadPanel() {
        initComponents();
    }
    
    void setPropiedad(CasillaCalle titulo){
        tituloPropiedad = titulo;
        nombrePropiedad.setText(titulo.getNombre());
        numcasas.setText(Integer.toString(titulo.getNumCasas()));
        numhoteles.setText(Integer.toString(titulo.getNumHoteles()));
        
        this.repaint();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        nombrePropiedad = new javax.swing.JTextField();
        casas = new javax.swing.JLabel();
        hoteles = new javax.swing.JLabel();
        numcasas = new javax.swing.JTextField();
        numhoteles = new javax.swing.JTextField();

        jLabel1.setText("Nombre");

        nombrePropiedad.setEditable(false);
        nombrePropiedad.setColumns(5);

        casas.setText("Casas");

        hoteles.setText("Hoteles");

        numcasas.setEditable(false);
        numcasas.setColumns(5);

        numhoteles.setEditable(false);
        numhoteles.setColumns(5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(nombrePropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(casas)
                .addGap(18, 18, 18)
                .addComponent(numcasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(hoteles)
                .addGap(27, 27, 27)
                .addComponent(numhoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nombrePropiedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(casas)
                    .addComponent(numcasas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hoteles)
                    .addComponent(numhoteles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel casas;
    private javax.swing.JLabel hoteles;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nombrePropiedad;
    private javax.swing.JTextField numcasas;
    private javax.swing.JTextField numhoteles;
    // End of variables declaration//GEN-END:variables
}
